version: '3.8'

services:
  user-service:
    build: ./services/user-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=users_db

  rag-service:
    build: ./services/rag-service
    ports:
      - "8001:8000"
    depends_on:
      - vector-db
    environment:
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=6333

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - vector_data:/qdrant/storage

volumes:
  postgres_data:
  vector_data: