global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "traefik"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:8000"]

  - job_name: "worker-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker-service:8000"]

  - job_name: "rag-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["rag-service:8000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "alerts.yml"
