"""Initial migration

Revision ID: 8eb11c7fe591
Revises: 
Create Date: 2025-03-03 21:58:49.763786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb11c7fe591'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=30), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=30), nullable=True),
    sa.Column('apellidos', sa.String(length=60), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMENINO', 'NO_BINARIO', 'PREFIERO_NO_REPORTAR', name='generodb'), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('celular', sa.String(length=10), nullable=False),
    sa.Column('nro_documento', sa.String(length=10), nullable=False),
    sa.Column('tipo_documento', sa.Enum('TARJETA_IDENTIDAD', 'CEDULA', name='tipodocumentodb'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nro_documento')
    )
    op.create_index('idx_correo', 'personas', ['correo'], unique=False)
    op.create_index('idx_nro_documento', 'personas', ['nro_documento'], unique=False)
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_index('idx_nro_documento', table_name='personas')
    op.drop_index('idx_correo', table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
