services:
  rag-service:
    build: .
    ports:
      - "8001:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=gpt-3.5-turbo
    volumes:
      - .:/app
    depends_on:
      - user-service

  user-service:
    image: user-service:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
